# Generated by Django 4.2.7 on 2023-11-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_projecttracker_developer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttracker',
            old_name='developer',
            new_name='leader',
        ),
        migrations.RemoveField(
            model_name='projecttracker',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='projecttracker',
            name='priority',
        ),
        migrations.AddField(
            model_name='projecttracker',
            name='actual_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttracker',
            name='base_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttracker',
            name='lab',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projecttracker',
            name='mag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projecttracker',
            name='projectId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projecttracker',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
