# Generated by Django 4.2.7 on 2023-11-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_rename_developer_projecttracker_leader_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttracker',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
