# Generated by Django 4.2.7 on 2023-11-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_projecttracker_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttracker',
            name='lab',
            field=models.CharField(blank=True, choices=[('All', 'All'), ('PML', 'PML'), ('RML', 'RML'), ('SPL', 'SPL'), ('TBA', 'TBA')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='projecttracker',
            name='mag',
            field=models.CharField(blank=True, choices=[('QL Goal', 'QL Goal'), ('RE2-GAN', 'RE2 GAN'), ('R73 Auto/R1 MOS', 'R73 Auto/R1 MOS'), ('RE1 PowerMos', 'RE1 PowerMos')], max_length=50, null=True),
        ),
    ]
