# Generated by Django 4.2.7 on 2023-11-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_projecttracker_lab_alter_projecttracker_mag'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
