# Generated by Django 4.2.7 on 2023-11-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_infoproject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infoproject',
            old_name='description',
            new_name='purpose',
        ),
        migrations.AddField(
            model_name='infoproject',
            name='CapEx_Ref',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='infoproject',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='infoproject',
            name='measurement_method',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='infoproject',
            name='requested_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
