# Generated by Django 4.2.7 on 2023-11-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_rename_description_infoproject_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoproject',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infoproject',
            name='level',
            field=models.CharField(blank=True, choices=[('GaN Program', 'GaN Program'), ('Project', 'Project')], max_length=50, null=True),
        ),
    ]
