# Generated by Django 4.1.3 on 2023-11-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_infoproject_comment_alter_infoproject_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttracker',
            name='nextgate',
            field=models.CharField(blank=True, choices=[('S Gate', 'S Gate'), ('A Gate', 'A Gate'), ('V Gate', 'V Gate'), ('R Gate', 'R Gate')], default='NOT STARTED', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projecttracker',
            name='nextgate_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
