# Generated by Django 4.1.3 on 2023-11-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_projecttracker_nextgate_projecttracker_nextgate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttracker',
            name='nextgate',
            field=models.CharField(blank=True, choices=[('S Gate', 'S Gate'), ('A Gate', 'A Gate'), ('V Gate', 'V Gate'), ('R Gate', 'R Gate')], default='S Gate', max_length=50, null=True),
        ),
    ]
