# Generated by Django 4.1.3 on 2023-11-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_alter_projecttracker_nextgate'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttracker',
            name='agate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttracker',
            name='rgate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttracker',
            name='vgate_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
