# Generated by Django 4.1.3 on 2023-11-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_projecttracker_agate_date_projecttracker_rgate_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttracker',
            name='sgate_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
