# Generated by Django 4.2.7 on 2023-11-15 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_alter_projecttracker_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttracker',
            name='start_date',
        ),
    ]
