# Generated by Django 4.2.7 on 2023-11-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_remove_projecttracker_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttracker',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
