# Generated by Django 4.2.7 on 2023-11-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_remove_projecttracker_agate_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoproject',
            name='sgate_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
