# Generated by Django 4.2.7 on 2023-11-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_infoproject_sgate_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoproject',
            name='rgate_date',
        ),
    ]
