# Generated by Django 4.2.7 on 2023-11-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0023_remove_infoproject_rgate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttracker',
            name='CapEx_Ref',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='projecttracker',
            name='agate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttracker',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttracker',
            name='currentForecast',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttracker',
            name='lastUpdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttracker',
            name='level',
            field=models.CharField(blank=True, choices=[('GaN Program', 'GaN Program'), ('Project', 'Project')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projecttracker',
            name='measurement_method',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='projecttracker',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttracker',
            name='qualityEng',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projecttracker',
            name='reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projecttracker',
            name='sgate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttracker',
            name='support',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projecttracker',
            name='testEng',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projecttracker',
            name='vgate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='InfoProject',
        ),
    ]
