# Generated by Django 4.2.7 on 2023-11-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_projecttracker_capex_ref_projecttracker_agate_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttracker',
            old_name='sgate_date',
            new_name='actual_agate_date',
        ),
        migrations.AddField(
            model_name='projecttracker',
            name='actual_sgate_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttracker',
            name='actual_vgate_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
