# Generated by Django 4.2.7 on 2023-11-17 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_rename_sgate_date_projecttracker_actual_agate_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projecttracker',
            old_name='actual_date',
            new_name='actual_rgate_date',
        ),
        migrations.RenameField(
            model_name='projecttracker',
            old_name='base_date',
            new_name='rgate_date',
        ),
        migrations.RenameField(
            model_name='projecttracker',
            old_name='start_date',
            new_name='sgate_date',
        ),
    ]
