# Generated by Django 4.2.7 on 2023-11-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0026_rename_actual_date_projecttracker_actual_rgate_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttracker',
            name='status',
            field=models.CharField(blank=True, choices=[('COMPLETED', 'COMPLETED'), ('NOT STARTED', 'NOT STARTED'), ('CANCELED', 'CANCELED'), ('STARTED', 'STARTED'), ('ON TIME', 'ON TIME'), ('SLIGHT DELAY', 'SLIGHT DELAY')], default='NOT STARTED', max_length=50, null=True),
        ),
    ]
