# Generated by Django 4.2.7 on 2023-11-20 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0027_alter_projecttracker_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttracker',
            name='status',
            field=models.CharField(blank=True, choices=[('COMPLETED', 'COMPLETED'), ('NOT STARTED', 'NOT STARTED'), ('CANCELED', 'CANCELED'), ('STARTED', 'STARTED'), ('ON TIME', 'ON TIME'), ('DELAY', 'DELAY')], default='NOT STARTED', max_length=50, null=True),
        ),
    ]
