# Generated by Django 4.2.7 on 2023-11-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0031_alter_projecttracker_capex_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
