# Generated by Django 4.1.3 on 2023-11-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0035_projecttracker_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttracker',
            name='champion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projecttracker',
            name='deliveryPlan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
